#:schema node_modules/wrangler/config-schema.json
name = "recursive-fetcher-do"
main = "worker.ts"
compatibility_date = "2025-01-09"

assets = { directory = "./public" }


routes = [
  { pattern = "dodfetch.claudeflair.com", custom_domain = true }
]

[durable_objects]
bindings = [{ name = "RECURSIVE_FETCHER", class_name = "RecursiveFetcherDO" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RecursiveFetcherDO"]